[package]
name = "cerbero-lib"
description = "Kerberos protocol attacker library"
version = "0.0.20"
authors = [ "Sabrina Andersen <NukingDragons>", "Eloy <zer1t0ps@protonmail.com>"]
edition = "2021"
license = "AGPL-3.0"
repository = "https://github.com/NukingDragons/cerbero-lib"
readme = "README.md"

[dependencies]
kerbeiros = "0.2"
kerberos_asn1 = "0.2"
kerberos_constants = "0.0"
kerberos_crypto = "0.3"
kerberos_ccache = "0.0"
kerberos_keytab = "0.0"
ms_pac = "0.0"
ms_dtyp = "0.0"
ms_samr = "0.0"
chrono = "0.4"
rand = "0.6"
trust-dns-resolver = "0.20"
